In [1]:
import pandas as pd
import numpy as np

df = pd.read_csv("spam.csv")
df.head()



Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [2]:
df.Category.value_counts()

Category
ham     4825
spam     747
Name: count, dtype: int64

In [3]:
df["spam"] = df['Category'].apply(lambda x : 1 if x == 'spam' else 0)

In [4]:
df.head()

Category                                            Message  spam
0      ham  Go until jurong point, crazy.. Available only ...     0
1      ham                      Ok lar... Joking wif u oni...     0
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...     1
3      ham  U dun say so early hor... U c already then say...     0
4      ham  Nah I don't think he goes to usf, he lives aro...     0

In [10]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(df.Message, df.spam, test_size = 0.2)

X_train.shape

(4457,)

In [11]:
type(X_train)

pandas.core.series.Series

In [12]:
X_train[:4]

987     I'm in office now . I will call you  &lt;#&gt;...
2269                    88066 FROM 88066 LOST 3POUND HELP
4875                     Wat happened to the cruise thing
94      Havent planning to buy later. I check already ...
Name: Message, dtype: object

In [13]:
type(y_train)

pandas.core.series.Series

In [15]:
y_train[:4]

987     0
2269    1
4875    0
94      0
Name: spam, dtype: int64

In [17]:
from sklearn.feature_extraction.text import CountVectorizer

v = CountVectorizer()

X_train_cv = v.fit_transform(X_train.values)


In [21]:
X_train_cv.toarray()

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], shape=(4457, 7684))

In [22]:
dir(v)

['_CountVectorizer__metadata_request__fit',
 '_CountVectorizer__metadata_request__transform',
 '__annotations__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__module__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setstate__',
 '__sizeof__',
 '__sklearn_clone__',
 '__sklearn_tags__',
 '__str__',
 '__subclasshook__',
 '__weakref__',
 '_build_request_for_signature',
 '_char_ngrams',
 '_char_wb_ngrams',
 '_check_stop_words_consistency',
 '_check_vocabulary',
 '_count_vocab',
 '_doc_link_module',
 '_doc_link_template',
 '_doc_link_url_param_generator',
 '_get_default_requests',
 '_get_doc_link',
 '_get_metadata_request',
 '_get_param_names',
 '_get_params_html',
 '_html_repr',
 '_limit_features',
 '_parameter_constraints',
 '_repr_html_',
 '_repr_html_inner',
 '_repr

In [23]:
v.vocabulary_

{'in': 3627,
 'office': 4863,
 'now': 4804,
 'will': 7460,
 'call': 1605,
 'you': 7646,
 'lt': 4228,
 'gt': 3239,
 'min': 4445,
 '88066': 697,
 'from': 2996,
 'lost': 4192,
 '3pound': 469,
 'help': 3378,
 'wat': 7335,
 'happened': 3308,
 'to': 6892,
 'the': 6772,
 'cruise': 2069,
 'thing': 6802,
 'havent': 3340,
 'planning': 5197,
 'buy': 1578,
 'later': 4009,
 'check': 1753,
 'already': 914,
 'lido': 4077,
 'only': 4904,
 'got': 3180,
 '530': 555,
 'show': 6092,
 'afternoon': 844,
 'finish': 2839,
 'work': 7533,
 'it': 3741,
 'wont': 7522,
 'until': 7127,
 '15': 304,
 'as': 1079,
 'trying': 7010,
 'sort': 6290,
 'house': 3496,
 'out': 4971,
 'is': 3729,
 'that': 6769,
 'ok': 4878,
 'hey': 3399,
 'babe': 1178,
 'saw': 5888,
 'came': 1624,
 'online': 4902,
 'for': 2917,
 'second': 5936,
 'and': 956,
 'then': 6785,
 'disappeared': 2315,
 'what': 7414,
 'dip': 2304,
 'cell': 1707,
 'dead': 2161,
 'so': 6245,
 'coming': 1898,
 'with': 7489,
 'him': 3412,
 'better': 1329,
 'respond': 5704,


In [25]:
X_train_np = X_train_cv.toarray()
X_train_np[0]

array([0, 0, 0, ..., 0, 0, 0], shape=(7684,))

In [26]:
from sklearn.naive_bayes import MultinomialNB

model = MultinomialNB()
model.fit(X_train_cv, y_train)

MultinomialNB()

In [27]:
X_test_cv = v.transform(X_test)

In [29]:
from sklearn.metrics import classification_report

y_pred = model.predict(X_test_cv)
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.99      0.99      0.99       981
           1       0.95      0.90      0.93       134

    accuracy                           0.98      1115
   macro avg       0.97      0.95      0.96      1115
weighted avg       0.98      0.98      0.98      1115



In [32]:
emails = [
    "Win money now!!!", 
    "Lowest price for your medicines", 
    "Hi friend, how are you?", 
    "Your account has been hacked, reset password", 
    "Meeting tomorrow at office", 
    "Congratulations, you won a free lottery ticket"
]

emails_count = v.transform(emails)
model.predict(emails_count)
    

array([0, 1, 0, 1, 0, 1])

In [5]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.pipeline import Pipeline
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import classification_report, accuracy_score, confusion_matrix

data = {
    "Message": [
        "Win money now!!!",
        "Hey, are we still meeting tomorrow?",
        "Limited offer, claim your prize",
        "Let's catch up over lunch",
        "Congratulations, you won a free ticket",
        "Can you send me the report?",
        "Urgent: Your account has been compromised",
        "See you at the game tonight"
    ],
    "spam": [1, 0, 1, 0, 1, 0, 1, 0]
}

df = pd.DataFrame(data)

X_train, X_test, y_train, y_test = train_test_split(
    df["Message"], df["spam"], test_size=0.3, random_state=42
)

clf = Pipeline([
    ('vectorizer', CountVectorizer()),
    ('nb', MultinomialNB())
])

clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)

print("Classification Report:\n", classification_report(y_test, y_pred))
print("Accuracy:", accuracy_score(y_test, y_pred))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))



Classification Report:
               precision    recall  f1-score   support

           0       1.00      0.50      0.67         2
           1       0.50      1.00      0.67         1

    accuracy                           0.67         3
   macro avg       0.75      0.75      0.67         3
weighted avg       0.83      0.67      0.67         3

Accuracy: 0.6666666666666666
Confusion Matrix:
 [[1 1]
 [0 1]]


In [6]:
# Test on new unseen messages
new_messages = [
    "Congratulations! You have won a free lottery ticket",
    "Can we meet tomorrow at 10am?",
    "Urgent: Update your bank details immediately",
    "Let's play chess after lunch"
]

predictions = clf.predict(new_messages)

for msg, label in zip(new_messages, predictions):
    print(f"{msg} --> {'Spam' if label == 1 else 'Not Spam'}")


Congratulations! You have won a free lottery ticket --> Spam
Can we meet tomorrow at 10am? --> Not Spam
Urgent: Update your bank details immediately --> Spam
Let's play chess after lunch --> Not Spam
